# Generated by Django 5.2.3 on 2025-06-25 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('delhivery', 'Delhivery'), ('xpressbees', 'Xpressbees')], default='delhivery', max_length=50)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_website', models.URLField(default='https://www.delhivery.com/')),
                ('shipping_label', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pickup_scheduled', max_length=50)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
