# Generated by Django 5.2.3 on 2025-06-30 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('original_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_version', to='product.productmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
