# Generated by Django 5.2.3 on 2025-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_use',
            field=models.PositiveIntegerField(default=1000000000),
        ),
    ]
