# Generated by Django 5.2.3 on 2025-06-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_min_order_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='couponuser',
            name='order',
        ),
    ]
