# Generated by Django 5.2.3 on 2025-06-26 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0004_alter_couponuser_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="value",
            field=models.DecimalField(default=0.00, max_digits=10, decimal_places=2),
            preserve_default=False,
        ),
    ]
