# Generated by Django 5.2.3 on 2025-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_coupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
